config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  # Nested routes for ebooks, recipes, and recipages
  # resources :recipes
  resources :ebooks, except: [:destroy] do
      resources :recipages, only: [:create]
    end

  resources :recipes do
    resources :recipages, only: [:show, :destroy, :create]
  end

  post "/transcribe_image" => "recipes#transcribe_image", :as => :transcribe_image

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ebook.rb
class Ebook < ApplicationRecord
  belongs_to :user
  has_many :recipages, dependent: :destroy
  has_many :recipes, through: :recipages
  validates :theme, presence: true
  validates :ebook_title, presence: true
  has_one_attached :photo
  accepts_nested_attributes_for :recipages

  before_create :associate_theme

  def dishes_count
    recipes.where(meal: 'Plat').count
  end

  def starters_count
    recipes.where(meal: 'Entrée').count
  end

  def desserts_count
    recipes.where(meal: 'Dessert').count
  end

  def associate_theme
    self.theme = (self.theme == "theme-1") ? "background-ilu.jpg" : "preview-ro.jpg"
  end
end

app/models/recipage.rb
class Recipage < ApplicationRecord
  require_dependency 'rmagick_service'

  belongs_to :recipe
  belongs_to :ebook
  has_one_attached :page
  has_one_attached :photo

  before_create :set_template

  def set_template
    RmagickService.new(self).create_image_with_text
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipages, dependent: :destroy
  has_many :ebooks, through: :recipages
  has_one_attached :photo
  validates :title, presence: true
  validates :meal, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_title_and_ingredient_and_instruction,
  against: [ :title, :ingredient, :meal, :instruction ],
  using: {
    tsearch: { prefix: true }
  }


  def set_content
    client = OpenAI::Client.new
    chaptgpt_response = client.chat(parameters: {
      model: "gpt-3.5-turbo",
      messages: [{
        role: "user",
        content: "renvoie moi au format JSON contenant ces clés: \"titre\", \"ingrédients\", \"étapes de préparation\" de la recette issu de ce lien: #{self.link_url}."
        }]
    })

    new_content = JSON.parse(chaptgpt_response["choices"][0]["message"]["content"])

     self.title = new_content["titre"]
     self.ingredient = new_content["ingrédients"].join("\n")
     self.instruction = new_content["étapes de préparation"].join("\n")
  end

  def set_content_by_image(picture_url)
    GptService.new(url: picture_url).call
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes
  has_many :ebooks
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/ebooks_controller.rb
class EbooksController < ApplicationController
  def show
    @ebook = Ebook.find(params[:id])
    @recipage = Recipage.new
    @recipages = @ebook.recipages
    render layout: 'application2'
  end

  def index
    @recipes_count = Recipe.count
    @ebooks_count = Ebook.count
    @printed_books_count = Ebook.count
    @ebooks = Ebook.all
  end

  def new
    # @recipes = Recipe.all
    @ebook = Ebook.new
  end

  def create
    @ebook = Ebook.new(ebook_params)
    @ebook.user = current_user
    if @ebook.save
      redirect_to ebook_path(@ebook)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def display_choice
    @templates = Ebook.select(:theme).distinct
  end

  def edit
    @ebook = Ebook.find(params[:id])
  end

  def update
    @ebook = Ebook.find(params[:id])
    if @ebook.update(ebook_params)
      redirect_to ebook_path(@ebook)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def ebook_params
    params.require(:ebook).permit(:ebook_title, :theme, recipe_ids: [])
  end
end

app/controllers/loading_controller.rb
class LoadingController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @recipe = Recipe.new
  end
end

app/controllers/recipages_controller.rb
class RecipagesController < ApplicationController
  require_dependency 'rmagick_service'

  def destroy
    @recipage = Recipage.find(params[:id])
    @ebook = @recipage.ebook
    @recipage.destroy
    redirect_to ebook_path(@ebook), status: :see_other
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipage = Recipage.new(recipage_params)
    @ebook = @recipage.ebook
    @recipage.recipe = @recipe
    if @recipage.save
      RmagickService.new(@recipage).create_image_with_text
      redirect_to @ebook
    else
      @recipages = @ebook.recipages
      render layout: 'application2'
      render ""
    end
  end

  private

  def recipage_params
    params.require(:recipage).permit(:templating, :recipe, :recipe_id, :ebook_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:destroy]


  def show
    @recipe = Recipe.find(params[:id])
  end

  def index
    @recipes = Recipe.all

    if params[:query].present?
      @recipes = @recipes.search_by_title_and_ingredient_and_instruction(params[:query])
    end

    if params[:meal].present? && params[:meal] != "Type de plat"
      @recipes = @recipes.where(meal: params[:meal])
    end
  end

  def new
    if params[:recipe] && recipe_params[:link_url]
      @recipe = Recipe.new(link_url: recipe_params[:link_url])
      @recipe.set_content
    elsif params[:recipe]
      @recipe = Recipe.new(recipe_params)
    else
      @recipe = Recipe.new(title: params[:title], ingredient: params[:ingredient], instruction: params[:instruction])
    end
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user

    if @recipe.save
      redirect_to @recipe, notice: "Recette bien créée"
    else
      render :new
    end
  end

  def transcribe_image
    transcribe_url = Cloudinary::Uploader.upload(params[:recipe][:photo].path)
    result = OpenaiService.new(url: transcribe_url["url"]).call
    redirect_to new_recipe_path(recipe: {
      title: result["title"],
      ingredient: result["ingredients"],
      instruction: result["preparation_steps"]
    })
  end

  def edit
    @recipe = Recipe.find(params[:id])
    @selected_meal = @recipe.meal
  end

  def update
    @recipe = Recipe.find(params[:id])

    if params[:recipe][:photo].present?
      upload_result = Cloudinary::Uploader.upload(params[:recipe][:photo].path)
      @recipe.picture_url = upload_result['secure_url']
    end

    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: "Recette bien mise à jour"
    else
      render :edit
    end
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_path, status: :see_other
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:title, :ingredient, :instruction, :meal, :photo, :link_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ebooks/_form.html.erb
 <%= simple_form_for(@ebook) do |f| %>
          <div class="control-label">
            <%= f.input :ebook_title, as: :text, label: "Titre", placeholder: "", input_html: { class: "form-field"} %>
          </div>

          <div class="form-container mb-5 d-flex justify-content-center theme-choice label-full-width control-label">

            <%= f.input :theme, as: :radio_buttons, input_html: { class: "image-radio-clickable"}, collection: [[image_tag("preview-ilu.jpg", size: "230x100"), "theme-1"], [image_tag("preview-ro.jpg", size: "230x100"), "theme-2"]] %>
          </div>


          <div class="text-center">
            <button type="button" class="btn btn-primary rounded-5 open-modal-black mb-1" data-bs-toggle="modal" data-bs-target="#exampleModal">
                Choisissez vos recettes</button>
          </div>
          <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-content modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Sélectionnez des recettes</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                <div class="modal-body">
                <%# modal debut %>

                <%= f.input :recipe_ids,
                                    label: "Sélectionner les recettes à ajouter",
                                    as: :check_boxes,
                                    collection: Recipe.all.map{|recipe| [raw(render partial: "recipages", locals: {recipe: recipe }), recipe.id]},
                                    input_html: { data: {form_target: "input" }, class: "sr-only"},
                                    item_label_class: "form-check-label w-100",
                                    wrapper_class: "row mx-0",
                                    item_wrapper_class: "col-12  recipe-modal-card-check" %>

                    <%# modal fin %>
                </div>
                <div class="modal-footer">
                  <%= button_tag "Valider", type: "submit", class: "button-valid-list-blue rounded-5" %>
                </div>
            </div>
          </div>
      </div>
    </div>
        <% end %>
  </div>
</div>

<%# ancienne list de checkbox %>
<%# <div class="modal-body">
<%= f.input :recipe_ids, label:"", as: :check_boxes,  collection: Recipe.all %>
<%# </div> %>

 <%# <%= f.input :recipe_ids,
                    label: "Sélectionner les recettes à ajouter",
                    as: :check_boxes,
                    collection: Recipe.all.map{|recipe| [raw(render partial: "recipages", locals: {recipe: recipe }), recipe.id]},
                    input_html: { data: {form_target: "input" }, class: "sr-only"},
                    item_label_class: "form-check-label w-100",
                    wrapper_class: "row mx-0",
                    item_wrapper_class: "col-12"%>

app/views/ebooks/_recipages.html.erb
  <div class="d-flex flex-row align-items-center mx-0 p-3 card recipe-modal-card">
    <div class="card-image">
      <% if recipe.photo.attached? %>
        <%= image_tag recipe.photo, alt: recipe.title %>
      <% else %>
        <%= image_tag 'default_image4.jpg', class: "background-image" %>
      <% end %>
    </div>
    <div class="card-content pe-3">
      <h3><%= recipe.title %></h3>
    </div>
</div>

app/views/ebooks/edit.html.erb
<div class="container ebook-form form-background-grey py-4">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8 col-lg-6">
      <div class="form-frame">
       <%= link_to ebook_path do %>
          <i class="fa-regular fa-circle-xmark text-black"></i>
        <% end %>
        <h3 class="text-center mb-3">Modifiez votre Ebook</h3>
        <%= render "form", ebook: @ebook %>

app/views/ebooks/index.html.erb
<body class="unique-page-class">
  <div class="stats-card mt-2">
    <div class="stats-item">
      <p class="stats-number"><%= @recipes_count %></p>
      <p class="stats-label">recettes répertoriées</p>
    </div>
    <div class="stats-item">
      <p class="stats-number"><%= @ebooks_count %></p>
      <p class="stats-label">Ebook générés</p>
    </div>
    <div class="stats-item">
      <p class="stats-number"><%= @printed_books_count %></p>
      <p class="stats-label">Livres imprimés</p>
    </div>
  </div>
  <div class="mt-3 d-flex justify-content-center">
    <%= link_to "Créer un E-Book ", new_ebook_path, class: "btn btn-ghost bg-white border-0 button-padding-top" %>
  </div>
  <div>
    <h3 class="mb-3 mt-3 ms-3 text-white">Mes E-Books</h3>
  </div>
  <% @ebooks.each do |ebook| %>
      <%= link_to ebook_path(ebook), class: "stats-big-card-link" do %>
        <div class="stats-big-card mt-3">
          <div class="image-container-card">
            <%= image_tag(ebook.associate_theme, alt: 'background-ilu') %>
          </div>
          <div class="text-container mt-2">
            <h2><%= ebook.ebook_title %></h2>
            <div class="info mb-4">
              <span><%= ebook.dishes_count %> plats</span>
              <span><%= ebook.starters_count %> entrées</span>
              <span><%= ebook.desserts_count %> desserts</span>
            </div>
          </div>
        </div>
      <% end %>
  <% end %>
</body>

app/views/ebooks/new.html.erb
<div class="container ebook-form form-background-grey py-4">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8 col-lg-6">
      <div class="form-frame">
       <%= link_to ebooks_path do %>
          <i class="fa-regular fa-circle-xmark text-black"></i>
        <% end %>
        <h3 class="text-center mb-3">Créez votre Ebook</h3>
       <%= render "form", ebook: @ebook %>

app/views/ebooks/show.html.erb
<div class="container ebook-display">
  <div class="row d-flex justify-content-center align-items-center pt-3">
    <div class="arrow-button col-4 position-absolute">
      <%= link_to ebooks_path, class: "arrow-button" do %>
        <i class="fa-solid fa-arrow-left"></i>
      <% end %>
    </div>
    <div class="ebook-title col-8 text-center position-relative">
      <p> <%= @ebook.ebook_title %> </p>
    </div>
  </div>

  <div class="ebook-counter">
    <div class="info d-flex justify-content-center">
          <div class="div mx-1"> <span><%= @ebook.dishes_count %> plats - </span></div>
          <div class="div"><span><%= @ebook.starters_count %> entrées - </span></div>
          <div class="div mx-1"><span><%= @ebook.desserts_count %> desserts</span></div>
    </div>
  </div>

  <div class="gear-position">
    <div class="modify-button d-flex justify-content-flex-end" >
      <%= link_to edit_ebook_path, class: "gear-button rotating" do %>
        <i class="fa-solid fa-gear"style="width: 65px; height: 100px; line-height: 100px; text-align: center;"></i>
      <% end %>
    </div>
</div>

  <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <defs>
      <symbol id="arrow" viewBox="0 0 100 100">
        <path d="M12.5 45.83h64.58v8.33H12.5z"/>
          <path d="M59.17 77.92l-5.84-5.84L75.43 50l-22.1-22.08 5.84-5.84L87.07 50z"/>
      </symbol>
    </defs>
  </svg>


  <div class="div previsualisation">
    <div id="carouselExampleCaptions" class="carousel carousel-dark slide">
      <div class="carousel-inner">
      <% @ebook.recipages.each_with_index do |recipage, i| %>
        <div class="carousel-item <%= 'active' if i.zero? %>">
        <%# recipage templating %>
         <%# <%= image_tag 'Page0-ebook1.jpg', class: "d-block w-100"%>
         <% if recipage.photo.attached? && recipage.photo.key.present? %>
          <%= cl_image_tag recipage.photo.key, height: 550, width: 400, crop: :fit %>
         <% else %>
          <%= image_tag 'place-holder.jpg', height: 550, width: 400, crop: :fit %>
         <% end %>
          <div class="carousel-caption d-none d-md-block">
            <h5><%=recipage.recipe.title%></h5>
          </div>
        </div>
      <% end %>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>

<%#
    <!-- Livre virtuel avec pages -->
    <%= image_tag 'Page0-ebook1.jpg', class: "background-image" %>
  </div>




<div id="downloadModal" class="modal fade" tabindex="-1" aria-labelledby="downloadModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-body text-center">
        <p>Votre Ebook a bien été généré, retrouvez-le dans vos téléchargements !</p>
      </div>
    </div>
  </div>
</div>

  <div class="row justify-content-center align-items-flex-end;">
    <%= link_to "#", class: "download-ebook btn col-8", data: { toggle: "modal", target: "#downloadModal" } do %>
      Téléchargez votre Ebook
    <% end %>
  </div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CocotteProject</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "shared/logo" %>
  <%= render "shared/navbar" %>

<div class="layout-wrapper">
    <%= yield %>
    </div>
  </body>
</html>

app/views/recipes/edit.html.erb
<div class="container form-background-grey py-4">
  <div class="row justify-content-center blue-grey-background-form">
    <div class="col-12 col-md-8 col-lg-6">
      <div class="form-frame">
        <%= link_to recipe_path do %>
          <i class="fa-regular fa-circle-xmark text-black"></i>
        <% end %>
        <h3 class="mb-2 text-center">Modifiez votre recette</h3>
          <%= render "form", recipe: @recipe %>

app/views/recipes/index.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-6">
      <div class="form">
      <%= form_with url: recipes_path, method: :get, class: "form-control form-input d-flex" do %>
        <button type="submit" class="btn btn-default">
          <i class="fa fa-search"></i>
        </button>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control search-bar",
          placeholder: "Rechercher une recette..."
          %>
      <% end %>
      </div>
    </div>
  </div>


  <div class="mt-3 mb-3 d-flex justify-content-center">
    <div class="row" style="width: 100%; overflow-x: auto; white-space: nowrap;">
      <div class="filter-list col-auto">
        <% ["Type de plat", "Entrée", "Plat", "Dessert", "Boisson", "Snack", "Apéritifs", "Brunch"].each do |meal| %>
          <%= button_tag meal, type: 'button', class: "meal-button", data: { meal: meal } %>
        <% end %>
      </div>
    </div>
  </div>



  <div>
      <% @recipes.each do |recipe| %>
          <a href="<%= recipe_path(recipe) %>" class="card row mx-0">
            <div class="card-image col-4">
              <% if recipe.photo.attached? %>
                <%= image_tag recipe.photo, alt: recipe.title %>
              <% else %>
                <%= image_tag 'default_image4.jpg', class: "background-image" %>
              <% end %>
            </div>
            <div class="card-content col-8">
              <h3><%= recipe.title %></h3>
            </div>
          </a>
      <% end %>
  </div>

</div>


  <script>
    $(document).ready(function() {
      $('.meal-button').click(function() {
        var meal = $(this).data('meal');
        window.location.href = '<%= recipes_path %>?meal=' + meal;
      });
    });
  </script>

app/views/recipes/new.html.erb
<body id="no-scroll-page">
  <div class="container form-background-grey py-4">
    <div class="row justify-content-center blue-grey-background-form">
      <div class="col-12 col-md-8 col-lg-6">
        <div class="form-frame">
          <%= link_to recipes_path do %>
            <i class="fa-regular fa-circle-xmark text-black"></i>
          <% end %>
            <h3 class="mb-2 text-center"><strong>Importer une recette </strong></h3>
              <%= render "form", recipe: @recipe %>
</body>

app/views/recipes/show.html.erb
<body id="show-page">

<div class="container-show">
  <% if @recipe.photo.attached? %>
    <%= cl_image_tag @recipe.photo.key, class: "background-image" %>
  <% else %>
    <%= image_tag 'default_image4.jpg', class: "background-image" %>
  <% end %>

  <div class="top-bar row justify-content-between align-items-center">

    <div class="col-2">
        <%= link_to recipes_path, class: "delete-button" do %>
          <i class="fa-solid fa-arrow-left"></i>
        <% end %>
    </div>

    <div class="col-8 text-center">
        <h2 class="recipe-title-show"><%= @recipe.title %></h2>
    </div>

    <div class="col-2 icon-container text-right">
      <%= link_to edit_recipe_path(@recipe), class: "delete-button" do %>
        <i class="fa-solid fa-pencil"></i>
      <% end %>
      <%= link_to recipe_path(@recipe), data: { turbo_method: :delete, turbo_confirm: "Vous êtes sûr chef ? 👩‍🍳" }, class: "delete-button" do %>
        <i class="fa-solid fa-trash"></i>
      <% end %>
    </div>
  </div>

  <div class="absolute-show pb-4">
    <div class="transparent-div"></div>
    <div class="content-div">

      <div class="container-top-content row justify-content-between align-items-center">
        <div class="col-3">
        </div>

        <div class="handle-bar col-6 text-center">
          <i class="fa-solid fa-grip-lines"></i>
        </div>

        <div class="meal-label col-3 text-center">
          <%= @recipe.meal %>
        </div>
      </div>

      <h3>Ingrédients : </h3>
      <p><%= simple_format(@recipe.ingredient) %></p>
      <h3>Instructions : </h3>
      <p><%= simple_format(@recipe.instruction) %></p>

    </div>
  </div>
</div>
</body>

app/views/shared/_navbar.html.erb
<div class="wrapper">
  <div class="navbar">
    <%= link_to recipes_path do %>
      <i class="fas fa-home icon-home"></i>
    <% end %>
    <%= link_to ebooks_path do %>
      <i class="fa-solid fa-book icon-book"></i>
    <% end %>

    <div class="circle">
      <i class="fas fa-plus plus-icon"></i>
      <i class="fa-sharp fa-solid fa-pen social mt-2" data-link="/recipes/new"></i>
      <i class="fa-solid fa-link social mt-2" data-link="/recipes"></i>
      <i class="fa-solid fa-camera social mt-2" data-link="/recipes"></i>
    </div>
    <div class="circleBackground"></div>
  </div>
</div>

<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content" style="border-radius: 20px; box-shadow: 0px 8px 15px rgba(0, 0, 0, 0.1);">
      <div class="modal-header text-center">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="font-size: 0.7rem; margin-top: -30px;">
          <span aria-hidden="true">&times;</span>
        </button>
        <h5 class="modal-title mx-auto" id="uploadModalCenterTitle">
            <span style="font-size: 1.2em; font-weight: bold; color: #89AAC9;">Cocotte minute</span><br>
            Création de recette intelligente
          </h5>
      </div>
      <div class="modal-body">
        <%= simple_form_for Recipe.new, url: new_recipe_path, method: "GET" do |f| %>
          <%= f.input :link_url, label: "Entrez le lien de votre recette ci-dessous et Cocotte s'occupera de tout.", input_html: { placeholder: "https://..." } %>
          <div class="d-flex justify-content-end mt-3">
            <%= f.button :submit, "À table !", class: "btn", style: "background-color: #89AAC9; border: none; box-shadow: 0px 8px 15px rgba(0, 0, 0, 0.1); transition: background-color 0.3s ease;" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>



<div class="modal fade" id="uploadModalCenter" tabindex="-1" role="dialog" aria-labelledby="uploadModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content" style="border-radius: 20px; box-shadow: 0px 8px 15px rgba(0, 0, 0, 0.1);">
      <div class="modal-header text-center">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="font-size: 0.7rem; margin-top: -30px;">
          <span aria-hidden="true">&times;</span>
        </button>
        <h5 class="modal-title" id="uploadModalCenterTitle">
          <span style="font-size: 1.2em; font-weight: bold; color: #89AAC9;">Cocotte magique</span><br>
          Transcription de recette manuscrite
        </h5>
      </div>
      <div class="modal-body">
        <%= simple_form_for Recipe.new, url: transcribe_image_path, method: 'POST', html: { class: 'form-horizontal', multipart: true } do |f| %>
          <div class="form-group row">
            <div class="col-12 mb-3">
              <p style="margin-bottom: 20px;">Importez la photo d'une recette et Cocotte s'occupera du reste.</p>
              <%= f.input :photo, as: :file, input_html: { class: 'form-control-file' }, label: false %>
            </div>
            <div class="col-12 text-center">
              <%= f.button :submit, "En cuisine !", class: "btn", style: "background-color: #89AAC9; border: none; box-shadow: 0px 8px 15px rgba(0, 0, 0, 0.1); transition: background-color 0.3s ease;" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>









<script>
  var icons = document.querySelectorAll(".circle i");

  icons.forEach(function(icon) {
    icon.addEventListener("click", function() {
      var link = this.getAttribute("data-link");
      if (this.classList.contains("fa-link")) {
        // Open the modal using Bootstrap's modal function
        $('#exampleModalCenter').modal('show');
      } else if (this.classList.contains("fa-camera")) {
        // Open the upload modal using Bootstrap's modal function
        $('#uploadModalCenter').modal('show');
      } else {
        // Redirect to the link
        window.location.href = link;
      }
    });
  });

  document.addEventListener("DOMContentLoaded", function() {
    // Use Bootstrap's modal function to close the modals
    var closeBtns = document.querySelectorAll(".modal .close");
    closeBtns.forEach(function(closeBtn) {
      closeBtn.addEventListener("click", function() {
        var modal = closeBtn.closest(".modal");
        $(modal).modal('hide');
      });
    });

    // Close the modals when clicking outside of them using Bootstrap's event
    $('.modal').on('hidden.bs.modal', function (e) {
      $(this).modal('hide');
    });

    window.addEventListener("click", function(event) {
      var modals = document.querySelectorAll(".modal");
      modals.forEach(function(modal) {
        if (event.target == modal) {
          $(modal).modal('hide');
        }
      });
    });
  });
</script>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>